[package]
name = "tailor"
version = "0.1.0"
authors = ["Alexander Pavel <alex.pavel@coreos.com>"]

[dependencies]
chrono = { version = "*", features = ["serde"] }
clap = "*"
error-chain = "*"
github-rs = { git = "https://github.com/mgattozzi/github-rs.git" }
iron = "*"
nom = "*"
persistent = "*"
regex = "*"
router = "*"
serde = "*"
serde_derive = "*"
serde_json = "*"
serde_yaml = "*"
